export const AVAILABLE_LANGUAGES = [
  // --- اللغة العربية (علم السعودية) ---
  { code: 'ar', name: 'العربية (الفصحى)', flag: '🇸🇦' },

  // --- اللغات العالمية والشرق أوسطية ---
  { code: 'en-US', name: 'English (United States)', flag: '🇺🇸' },
  { code: 'en-GB', name: 'English (United Kingdom)', flag: '🇬🇧' },
  { code: 'en-AU', name: 'English (Australia)', flag: '🇦🇺' },
  { code: 'en-CA', name: 'English (Canada)', flag: '🇨🇦' },
  { code: 'en-IN', name: 'English (India)', flag: '🇮🇳' },
  { code: 'es-ES', name: 'Español (España)', flag: '🇪🇸' },
  { code: 'es-MX', name: 'Español (México)', flag: '🇲🇽' },
  { code: 'fr-FR', name: 'Français (France)', flag: '🇫🇷' },
  { code: 'fr-CA', name: 'Français (Canada)', flag: '🇨🇦' },
  { code: 'de-DE', name: 'Deutsch (Deutschland)', flag: '🇩🇪' },
  { code: 'it-IT', name: 'Italiano (Italia)', flag: '🇮🇹' },
  { code: 'pt-BR', name: 'Português (Brasil)', flag: '🇧🇷' },
  { code: 'pt-PT', name: 'Português (Portugal)', flag: '🇵🇹' },
  { code: 'ru-RU', name: 'Русский (Россия)', flag: '🇷🇺' },
  { code: 'zh-CN', name: '中文 (简体)', flag: '🇨🇳' },
  { code: 'zh-TW', name: '中文 (繁體)', flag: '🇹🇼' },
  { code: 'ja-JP', name: '日本語 (日本)', flag: '🇯🇵' },
  { code: 'ko-KR', name: '한국어 (대한민국)', flag: '🇰🇷' },
  { code: 'tr-TR', name: 'Türkçe (Türkiye)', flag: '🇹🇷' },
  { code: 'fa-IR', name: 'فارسی (ایران)', flag: '🇮🇷' },
  { code: 'ur-PK', name: 'اردو (پاکستان)', flag: '🇵🇰' },
  { code: 'hi-IN', name: 'हिन्दी (भारत)', flag: '🇮🇳' },
  { code: 'bn-BD', name: 'বাংলা (বাংলাদেশ)', flag: '🇧🇩' },

  // --- اللغات الأوروبية ---
  { code: 'nl-NL', name: 'Nederlands (Nederland)', flag: '🇳🇱' },
  { code: 'pl-PL', name: 'Polski (Polska)', flag: '🇵🇱' },
  { code: 'sv-SE', name: 'Svenska (Sverige)', flag: '🇸🇪' },
  { code: 'no-NO', name: 'Norsk (Norge)', flag: '🇳🇴' },
  { code: 'da-DK', name: 'Dansk (Danmark)', flag: '🇩🇰' },
  { code: 'fi-FI', name: 'Suomi (Suomi)', flag: '🇫🇮' },
  { code: 'el-GR', name: 'Ελληνικά (Ελλάδα)', flag: '🇬🇷' },
  { code: 'cs-CZ', name: 'Čeština (Česko)', flag: '🇨🇿' },
  { code: 'hu-HU', name: 'Magyar (Magyarország)', flag: '🇭🇺' },
  { code: 'ro-RO', name: 'Română (România)', flag: '🇷🇴' },
  { code: 'uk-UA', name: 'Українська (Україна)', flag: '🇺🇦' },
  { code: 'bg-BG', name: 'Български (България)', flag: '🇧🇬' },
  { code: 'hr-HR', name: 'Hrvatski (Hrvatska)', flag: '🇭🇷' },
  { code: 'sk-SK', name: 'Slovenčina (Slovensko)', flag: '🇸🇰' },
  { code: 'sr-RS', name: 'Српски (Србија)', flag: '🇷🇸' },
  { code: 'sl-SI', name: 'Slovenščina (Slovenija)', flag: '🇸🇮' },
  { code: 'et-EE', name: 'Eesti (Eesti)', flag: '🇪🇪' },
  { code: 'lv-LV', name: 'Latviešu (Latvija)', flag: '🇱🇻' },
  { code: 'lt-LT', name: 'Lietuvių (Lietuva)', flag: '🇱🇹' },
  { code: 'is-IS', name: 'Íslenska (Ísland)', flag: '🇮🇸' },
  { code: 'ga-IE', name: 'Gaeilge (Éire)', flag: '🇮🇪' },
  { code: 'mt-MT', name: 'Malti (Malta)', flag: '🇲🇹' },
  { code: 'sq-AL', name: 'Shqip (Shqipëri)', flag: '🇦🇱' },
  { code: 'mk-MK', name: 'Македонски (Македонија)', flag: '🇲🇰' },
  { code: 'bs-BA', name: 'Bosanski (Bosna i Hercegovina)', flag: '🇧🇦' },
  { code: 'ca-ES', name: 'Català (Espanya)', flag: '🇪🇸' },
  { code: 'eu-ES', name: 'Euskara (Espainia)', flag: '🇪🇸' },
  { code: 'gl-ES', name: 'Galego (España)', flag: '🇪🇸' },
  { code: 'cy-GB', name: 'Cymraeg (Y Deyrnas Unedig)', flag: '🇬🇧' },
  { code: 'be-BY', name: 'Беларуская (Беларусь)', flag: '🇧🇾' },

  // --- لغات آسيا وباقي القارات ---
  { code: 'id-ID', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms-MY', name: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'th-TH', name: 'ไทย (ประเทศไทย)', flag: '🇹🇭' },
  { code: 'vi-VN', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'fil-PH', name: 'Filipino (Pilipinas)', flag: '🇵🇭' },
  { code: 'sw-KE', name: 'Kiswahili (Kenya)', flag: '🇰🇪' },
  { code: 'hy-AM', name: 'Հայերեն (Հայաստան)', flag: '🇦🇲' },
  { code: 'ka-GE', name: 'ქართული (საქართველო)', flag: '🇬🇪' },
  { code: 'az-AZ', name: 'Azərbaycan dili', flag: '🇦🇿' },
  { code: 'kk-KZ', name: 'Қазақ тілі (Қазақстан)', flag: '🇰🇿' },
  { code: 'uz-UZ', name: "O'zbek tili (O'zbekiston)", flag: '🇺🇿' },
  { code: 'ky-KG', name: 'Кыргызча (Кыргызстан)', flag: '🇰🇬' },
  { code: 'tg-TJ', name: 'Тоҷикӣ (Тоҷикистон)', flag: '🇹🇯' },
  { code: 'tk-TM', name: 'Türkmen dili (Türkmenistan)', flag: '🇹🇲' },
  { code: 'mn-MN', name: 'Монгол хэл (Монгол)', flag: '🇲🇳' },
  { code: 'my-MM', name: 'မြန်မာဘာသာ (မြန်မာ)', flag: '🇲🇲' },
  { code: 'km-KH', name: 'ភាសាខ្មែរ (កម្ពុជា)', flag: '🇰🇭' },
  { code: 'lo-LA', name: 'ພາສາລາວ (ລາວ)', flag: '🇱🇦' },
  { code: 'ne-NP', name: 'नेपाली (नेपाल)', flag: '🇳🇵' },
  { code: 'si-LK', name: 'සිංහල (ශ්‍රී ලංකාව)', flag: '🇱🇰' },
  { code: 'pa-IN', name: 'ਪੰਜਾਬੀ (ਭਾਰਤ)', flag: '🇮🇳' },
  { code: 'gu-IN', name: 'ગુજરાતી (ભારત)', flag: '🇮🇳' },
  { code: 'ta-IN', name: 'தமிழ் (இந்தியா)', flag: '🇮🇳' },
  { code: 'te-IN', name: 'తెలుగు (భారతదేశం)', flag: '🇮🇳' },
  { code: 'kn-IN', name: 'ಕನ್ನಡ (ಭಾರತ)', flag: '🇮🇳' },
  { code: 'ml-IN', name: 'മലയാളം (ഇന്ത്യ)', flag: '🇮🇳' },
  { code: 'mr-IN', name: 'मराठी (भारत)', flag: '🇮🇳' },

  // --- لغات أفريقيا والأمريكتين وباقي العالم ---
  { code: 'af-ZA', name: 'Afrikaans (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'am-ET', name: 'አማርኛ (ኢትዮጵያ)', flag: '🇪🇹' },
  { code: 'ha-NG', name: 'Hausa (Najeriya)', flag: '🇳🇬' },
  { code: 'yo-NG', name: 'Yorùbá (Nàìjíríà)', flag: '🇳🇬' },
  { code: 'ig-NG', name: 'Asụsụ Igbo (Naịjirịa)', flag: '🇳🇬' },
  { code: 'zu-ZA', name: 'isiZulu (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'xh-ZA', name: 'isiXhosa (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'so-SO', name: 'Soomaali (Soomaaliya)', flag: '🇸🇴' },
  { code: 'mg-MG', name: 'Malagasy (Madagasikara)', flag: '🇲🇬' },
  { code: 'sn-ZW', name: 'chiShona (Zimbabwe)', flag: '🇿🇼' },
  { code: 'rw-RW', name: 'Kinyarwanda (Rwanda)', flag: '🇷🇼' },
  { code: 'ny-MW', name: 'Chichewa (Malawi)', flag: '🇲🇼' },
  { code: 'st-LS', name: 'Sesotho (Lesotho)', flag: '🇱🇸' },
  { code: 'tn-BW', name: 'Setswana (Botswana)', flag: '🇧🇼' },

  // --- لغات إضافية عالمية للتغطية الشاملة ---
  { code: 'la', name: 'Lingua Latina', flag: '🇻🇦' },
  { code: 'eo', name: 'Esperanto', flag: '🌐' },
  { code: 'jv-ID', name: 'Basa Jawa (Indonesia)', flag: '🇮🇩' },
  { code: 'su-ID', name: 'Basa Sunda (Indonesia)', flag: '🇮🇩' },
  { code: 'ceb-PH', name: 'Sinugboanon (Pilipinas)', flag: '🇵🇭' },
  { code: 'haw-US', name: 'ʻŌlelo Hawaiʻi (United States)', flag: '🇺🇸' },
  { code: 'mi-NZ', name: 'Te Reo Māori (Aotearoa)', flag: '🇳🇿' },
  { code: 'sm-WS', name: 'Gagana Samoa (Samoa)', flag: '🇼🇸' },
  { code: 'to-TO', name: 'Lea Faka-Tonga (Tonga)', flag: '🇹🇴' },
  { code: 'ht-HT', name: 'Kreyòl Ayisyen (Haiti)', flag: '🇭🇹' },
  { code: 'fy-NL', name: 'Frysk (Nederland)', flag: '🇳🇱' },
  { code: 'gd-GB', name: 'Gàidhlig (Rìoghachd Aonaichte)', flag: '🇬🇧' },
  { code: 'yi', name: 'ייִדיש', flag: '🌐' },
  { code: 'ug-CN', name: 'ئۇيغۇرچە (جۇڭگو)', flag: '🇨🇳' },
  { code: 'ku-TR', name: 'Kurdî (Türkiye)', flag: '🇹🇷' },
  { code: 'ps-AF', name: 'پښتو (افغانستان)', flag: '🇦🇫' },
  { code: 'sd-PK', name: 'سنڌي (پاکستان)', flag: '🇵🇰' },
  { code: 'mni-IN', name: 'ꯃꯩꯇꯩꯂꯣꯟ (India)', flag: '🇮🇳' },
  { code: 'or-IN', name: 'ଓଡ଼ିଆ (ଭାରତ)', flag: '🇮🇳' },
  { code: 'as-IN', name: 'অসমীয়া (ভাৰত)', flag: '🇮🇳' },
  { code: 'mai-IN', name: 'मैथिली (भारत)', flag: '🇮🇳' },
  { code: 'sat-IN', name: 'ᱥᱟᱱᱛᱟᱲᱤ (India)', flag: '🇮🇳' },
  { code: 'doi-IN', name: 'डोगरी (भारत)', flag: '🇮🇳' },
  { code: 'ks-IN', name: 'کٲشُر (ہندوستان)', flag: '🇮🇳' },
  { code: 'sa-IN', name: 'संस्कृतम् (भारतम्)', flag: '🇮🇳' },
  { code: 'kok-IN', name: 'கொங்கணி (இந்தியா)', flag: '🇮🇳' },
  { code: 'br-FR', name: 'Brezhoneg (France)', flag: '🇫🇷' },
  { code: 'co-FR', name: 'Corsu (France)', flag: '🇫🇷' },
  { code: 'oc-FR', name: 'Occitan (France)', flag: '🇫🇷' },
  { code: 'rm-CH', name: 'Rumantsch (Svizra)', flag: '🇨🇭' },
  { code: 'lb-LU', name: 'Lëtzebuergesch (Lëtzebuerg)', flag: '🇱🇺' },
  { code: 'fo-FO', name: 'Føroyskt (Føroyar)', flag: '🇫🇴' },
  { code: 'kl-GL', name: 'Kalaallisut (Kalaallit Nunaat)', flag: '🇬🇱' },
  { code: 'tt-RU', name: 'Татар теле (Россия)', flag: '🇷🇺' },
  { code: 'ba-RU', name: 'Башҡорт теле (Россия)', flag: '🇷🇺' },
  { code: 'cv-RU', name: 'Чӑваш чӗлхи (Россия)', flag: '🇷🇺' },
  { code: 'sah-RU', name: 'Саха тыла (Россия)', flag: '🇷🇺' },
  { code: 'ce-RU', name: 'Нохчийн мотт (Россия)', flag: '🇷🇺' },
  { code: 'os-GE', name: 'Ирон æвзаг', flag: '🇬🇪' },
  { code: 'ab-GE', name: 'Апсуа бызшәа', flag: '🇬🇪' },
  { code: 'mvr-MV', name: 'ދިވެހިބަސް (ދިވެހިރާއްޖެ)', flag: '🇲🇻' },
  { code: 'dz-BT', name: 'རྫོང་ཁ (འབྲུག)', flag: '🇧🇹' },
  { code: 'ti-ET', name: 'ትግርኛ (ኤርትራ/ኢትዮጵያ)', flag: '🇪🇹' },
  { code: 'om-ET', name: 'Afaan Oromoo (Itoophiyaa)', flag: '🇪🇹' },
  { code: 'sid-ET', name: 'Sidaamu Afoo (Itoophiyaa)', flag: '🇪🇹' },
  { code: 'so-ET', name: 'Soomaali (Itoophiyaa)', flag: '🇪🇹' },
  { code: 'aa-DJ', name: 'Qafár af (Jibuti)', flag: '🇩🇯' },
  { code: 'lg-UG', name: 'Luganda (Uganda)', flag: '🇺🇬' },
  { code: 'run-BI', name: 'Ikirundi (Burundi)', flag: '🇧🇮' },
  { code: 'luo-KE', name: 'Dholuo (Kenya)', flag: '🇰🇪' },
  { code: 'kik-KE', name: 'Gĩkũyũ (Kenya)', flag: '🇰🇪' },
  { code: 'ts-ZA', name: 'Xitsonga (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'ss-ZA', name: 'SiSwati (Suid-Afrika)', flag: '🇿🇦' },
  { code: 've-ZA', name: 'Tshivenḓa (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'nso-ZA', name: 'Sepedi (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'nr-ZA', name: 'isiNdebele (Suid-Afrika)', flag: '🇿🇦' },
  { code: 'ee-GH', name: 'Eʋegbe (Ghana)', flag: '🇬🇭' },
  { code: 'ak-GH', name: 'Akan (Ghana)', flag: '🇬🇭' },
  { code: 'tw-GH', name: 'Twi (Ghana)', flag: '🇬🇭' },
  { code: 'gaa-GH', name: 'Ga (Ghana)', flag: '🇬🇭' },
  { code: 'bm-ML', name: 'Bamanankan (Mali)', flag: '🇲🇱' },
  { code: 'ff-SN', name: 'Fulfulde (Senegal)', flag: '🇸🇳' },
  { code: 'wo-SN', name: 'Wolof (Sénégal)', flag: '🇸🇳' },
  { code: 'kg-CD', name: 'Kikongo (RDC)', flag: '🇨🇩' },
  { code: 'ln-CD', name: 'Lingála (RDC)', flag: '🇨🇩' },
  { code: 'lua-CD', name: 'Tshiluba (RDC)', flag: '🇨🇩' },
  { code: 'swc-CD', name: 'Kiswahili (RDC)', flag: '🇨🇩' },
  { code: 'gn-PY', name: 'Avañe\'ẽ (Paraguay)', flag: '🇵🇾' },
  { code: 'qu-PE', name: 'Runa Simi (Perú)', flag: '🇵🇪' },
  { code: 'ay-BO', name: 'Aymar aru (Bolivia)', flag: '🇧🇴' },
  { code: 'arn-CL', name: 'Mapudungun (Chile)', flag: '🇨🇱' },
  { code: 'tzm-MA', name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ (المغرب)', flag: '🇲🇦' },
  { code: 'ber-DZ', name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ (الجزائر)', flag: '🇩🇿' }
];